### ISSUE TITLE
Python vm subprocess exit

### ISSUE THREAD

**Issue by tarrencev** [eqlabs/pathfinder#386]
Ran into these error logs when overloading the node with `starknet_calls`

```
2022-06-16T22:15:24.185975Z  INFO ext_py: Subprocess exited pid=2776 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=2
2022-06-16T22:15:24.326094Z  INFO ext_py: Subprocess exited pid=2773 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=2
2022-06-16T22:15:39.876882Z  INFO ext_py:subproc: Subprocess launched count=2 pid=2903
2022-06-16T22:15:41.131790Z  INFO ext_py:subproc: Subprocess launched count=2 pid=2904
2022-06-16T22:15:42.666174Z  INFO ext_py: Subprocess exited pid=2903 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=2
2022-06-16T22:15:45.324118Z  INFO ext_py: Subprocess exited pid=2904 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=2
2022-06-16T22:15:55.151317Z  INFO ext_py:subproc: Subprocess launched count=2 pid=2909
2022-06-16T22:15:58.868710Z  INFO ext_py:subproc: Subprocess launched count=2 pid=2910
2022-06-16T22:15:58.890023Z  INFO ext_py: Subprocess exited pid=2909 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=2
2022-06-16T22:16:06.646246Z  INFO ext_py: Subprocess exited pid=2910 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=2
```

Which results in the rpc request timing out.

**Comment by Mirko-von-Leipzig** [comment]
@koivunej any insight into what is going on here?

**Comment by koivunej** [comment]
After sending from rust to python a call request the cancelling of jsonrpsee method call will lead to rxpected logs: https://github.com/eqlabs/pathfinder/blob/82425d44d7aa148bd31a60a7823a3e42b8d613f4/crates/pathfinder/src/cairo/ext_py/sub_process.rs#L305

I guess we could have more complicated cancellation signalling and handling over at the python side but I don't know how could the execution be interrupted (reliably). Maybe with threads..

Killing the python when cancelled imposes a heavy start cost on next request handling which is unideal as well.

**Comment by koivunej** [comment]
Looking at this again, what happens is:
1. jsonrpsee times out
2. request handling future gets dropped
3. oneshot channel used to communicate with pythoner gets dropped
4. python is killed

I guess what is this really about is longer timeouts at the jsonrpc level? I cannot see any configuration and I guess I wouldn't really expect there to be such. Could it be the client who aborts the request? Could you give some reproducers to test out with? (Next release will have a very easy copy-paste way to provide these after tuning the logging.)

**Comment by tarrencev** [comment]
Adding some additional logs here, not sure if these are related or if it is a different issue:

```
22-07-07T18:05:39.937909Z ERROR ext_py:subproc:stderr: Traceback (most recent call last): count=25 pid=864
2022-07-07T18:05:39.938228Z ERROR ext_py:subproc:stderr: File "/tmp/.tmpTCvZsS", line 724, in <module> count=25 pid=864
2022-07-07T18:05:39.938389Z ERROR ext_py:subproc:stderr: File "/tmp/.tmpTCvZsS", line 51, in main count=25 pid=864
2022-07-07T18:05:39.938503Z ERROR ext_py:subproc:stderr: File "/tmp/.tmpTCvZsS", line 139, in do_loop count=25 pid=864
2022-07-07T18:05:39.938658Z ERROR ext_py:subproc:stderr: BrokenPipeError: [Errno 32] Broken pipe count=25 pid=864
2022-07-07T18:05:39.938786Z ERROR ext_py:subproc:stderr: Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> count=25 pid=864
2022-07-07T18:05:39.938963Z ERROR ext_py:subproc:stderr: BrokenPipeError: [Errno 32] Broken pipe count=25 pid=864
2022-07-07T18:05:40.083574Z ERROR ext_py:subproc:stderr: Traceback (most recent call last): count=25 pid=824
2022-07-07T18:05:40.083917Z ERROR ext_py:subproc:stderr: File "/tmp/.tmpezS0il", line 724, in <module> count=25 pid=824
2022-07-07T18:05:40.084040Z ERROR ext_py:subproc:stderr: File "/tmp/.tmpezS0il", line 51, in main count=25 pid=824
2022-07-07T18:05:40.084168Z ERROR ext_py:subproc:stderr: File "/tmp/.tmpezS0il", line 139, in do_loop count=25 pid=824
2022-07-07T18:05:40.084277Z ERROR ext_py:subproc:stderr: BrokenPipeError: [Errno 32] Broken pipe count=25 pid=824
2022-07-07T18:05:40.094125Z ERROR ext_py:subproc:stderr: Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> count=25 pid=824
2022-07-07T18:05:40.094442Z ERROR ext_py:subproc:stderr: BrokenPipeError: [Errno 32] Broken pipe count=25 pid=824
2022-07-07T18:05:40.325399Z  INFO ext_py: Subprocess exited pid=840 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:40.333250Z  INFO ext_py: Subprocess exited pid=864 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:40.384933Z  INFO ext_py: Subprocess exited pid=886 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:40.450385Z  INFO ext_py: Subprocess exited pid=891 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:40.463048Z  INFO ext_py: Subprocess exited pid=870 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:40.547580Z  INFO ext_py: Subprocess exited pid=897 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:40.549820Z  INFO ext_py: Subprocess exited pid=824 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:40.662999Z  INFO ext_py: Subprocess exited pid=879 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:40.665300Z  INFO ext_py: Subprocess exited pid=895 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:40.666885Z  INFO ext_py: Subprocess exited pid=881 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:40.682747Z  INFO ext_py: Subprocess exited pid=876 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:40.683734Z  INFO ext_py: Subprocess exited pid=867 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:40.691906Z  INFO ext_py: Subprocess exited pid=873 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:40.843490Z  INFO ext_py: Subprocess exited pid=920 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:40.965364Z  INFO ext_py: Subprocess exited pid=889 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:40.965740Z  INFO ext_py: Subprocess exited pid=884 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:41.007363Z  INFO ext_py: Subprocess exited pid=846 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:41.012426Z  INFO ext_py: Subprocess exited pid=900 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:41.135061Z  INFO ext_py: Subprocess exited pid=916 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:41.245534Z  INFO ext_py: Subprocess exited pid=910 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:41.339631Z  INFO ext_py: Subprocess exited pid=906 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:41.593831Z  INFO ext_py: Subprocess exited pid=924 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:41.722774Z  INFO ext_py: Subprocess exited pid=903 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:42.026288Z  INFO ext_py: Subprocess exited pid=838 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:42.170151Z  INFO ext_py: Subprocess exited pid=927 exit_status=Some(ExitStatus(unix_wait_status(9))) exit_reason=Cancellation count=25
2022-07-07T18:05:43.166616Z  INFO ext_py:subproc: Subprocess launched count=25 pid=947
2022-07-07T18:05:43.896684Z  INFO ext_py:subproc: Subprocess launched count=25 pid=949
2022-07-07T18:05:44.884613Z  INFO ext_py:subproc: Subprocess launched count=25 pid=953
2022-07-07T18:05:46.347707Z  INFO ext_py:subproc: Subprocess launched count=25 pid=956
2022-07-07T18:05:47.948446Z  INFO ext_py:subproc: Subprocess launched count=25 pid=959
2022-07-07T18:05:49.098283Z  INFO ext_py:subproc: Subprocess launched count=25 pid=961
2022-07-07T18:05:50.260902Z  INFO ext_py:subproc: Subprocess launched count=25 pid=964
2022-07-07T18:05:51.197743Z  INFO ext_py:subproc: Subprocess launched count=25 pid=967
2022-07-07T18:05:53.006897Z  INFO ext_py:subproc: Subprocess launched count=25 pid=971
2022-07-07T18:05:54.965145Z  INFO ext_py:subproc: Subprocess launched count=25 pid=975
2022-07-07T18:05:55.999509Z  INFO ext_py:subproc: Subprocess launched count=25 pid=977
2022-07-07T18:05:58.291442Z  INFO ext_py:subproc: Subprocess launched count=25 pid=980
2022-07-07T18:05:58.925809Z  INFO ext_py:subproc: Subprocess launched count=25 pid=986
2022-07-07T18:05:59.364654Z  INFO ext_py:subproc: Subprocess launched count=25 pid=983
2022-07-07T18:06:02.036380Z  INFO ext_py:subproc: Subprocess launched count=25 pid=989
2022-07-07T18:06:03.239185Z  INFO ext_py:subproc: Subprocess launched count=25 pid=991
2022-07-07T18:06:04.415822Z  INFO ext_py:subproc: Subprocess launched count=25 pid=996
2022-07-07T18:06:10.789188Z ERROR Sync process ended unexpected with: Err(Insert contract definition with hash: ClassHash(StarkHash(0x03CEC0ED5FEEDB872BB05394EA73E03DE583FC068043AE0C7961D066B522C6A1))
```

@koivunej to your question, it could be the client that is aborting the requests since they are taking so long to get serviced.

**Comment by koivunej** [comment]
First thing that comes to mind is that you are running quite a lot of processes. Do you have 25+ core machine? I would set at most core count python processes, they are mostly cpu intensive.

Next up the high amount of requests must be locking the database, causing the error saving contract definition. I think the last error message got cut with the paste, but you should set `--sqlite-wal true` or env variable or config file directive.

Having seen now your process counts now makes me think perhaps killing and respawning is not the right way to go, or at least the multiline default exception report needs to be gotten rid of.

**Comment by koivunej** [comment]
@tarrencev retrying mention, please see above?

**Comment by tarrencev** [comment]
hey @koivunej sorry i missed the first message. we're now running with `PATHFINDER_SQLITE_WAL="true"` and matching the python thread count to the cpu count. Things do seem much more stable now!
