### ISSUE TITLE
Python subproc error

### ISSUE THREAD

**Issue by tarrencev** [eqlabs/pathfinder#466]
Sharing a new error I've been seeing. I recently updated from 0.2.4 to 0.2.6. Not sure if it is related to that

```
2022-07-21T13:21:31.038327Z  INFO ext_py:subproc: Subprocess launched count=10 pid=381
2022-07-21T13:21:32.180770Z  INFO ext_py:subproc: Subprocess launched count=10 pid=383
2022-07-21T13:21:32.725600Z  INFO Updated StarkNet state with block 272890
2022-07-21T13:21:33.686458Z  INFO ext_py:subproc: Subprocess launched count=10 pid=388
2022-07-21T13:21:34.087314Z  INFO ext_py:subproc: Subprocess launched count=10 pid=392
2022-07-21T13:21:37.714011Z  INFO Updated StarkNet state with block 272891
2022-07-21T13:21:41.116728Z ERROR ext_py:subproc:stderr: Traceback (most recent call last): count=10 pid=381
2022-07-21T13:21:41.116875Z ERROR ext_py:subproc:stderr: File "/tmp/.tmpyqpelc", line 735, in <module> count=10 pid=381
2022-07-21T13:21:41.116950Z ERROR ext_py:subproc:stderr: File "/tmp/.tmpyqpelc", line 51, in main count=10 pid=381
2022-07-21T13:21:41.116975Z ERROR ext_py:subproc:stderr: File "/tmp/.tmpyqpelc", line 139, in do_loop count=10 pid=381
2022-07-21T13:21:41.117021Z ERROR ext_py:subproc:stderr: BrokenPipeError: [Errno 32] Broken pipe count=10 pid=381
2022-07-21T13:21:41.117412Z ERROR ext_py:subproc:stderr: Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> count=10 pid=381
2022-07-21T13:21:41.117630Z ERROR ext_py:subproc:stderr: BrokenPipeError: [Errno 32] Broken pipe count=10 pid=381
```

**Comment by kkovaacs** [comment]
I could reproduce the ERROR logs above by running the following:

```
curl --json '{"jsonrpc":"2.0","id":"34","method":"starknet_call","params":[{"calldata":["0x1234"],"contract_address":"0x6fbd460228d843b7fbef670ff15607bf72e19fa94de21e29811ada167b4ca39", "entry_point_selector":"0x362398bec32bc0ebb411203221a35a0301193a96f317ebe5e40be9f60d15320"}, "latest"]}' http://localhost:9545/ >/dev/null & sleep 0.01 && kill %
```

@tarrencev Do you also have log lines like this _after_ the BrokenPipeError logs?

```
2022-07-25T15:28:06.382633Z  INFO ext_py: Subprocess exited pid=41643 exit_status=Some(ExitStatus(unix_wait_status(30720))) exit_reason=Cancellation count=2
```

I just wanted to make sure that this is also triggered by cancellation in your case.
